spring.application.name=electro

spring.datasource.url=jdbc:postgresql://localhost:5432/electrodb
spring.datasource.username=postgres
spring.datasource.password=1111
#spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Server Configuration
server.port=8080
server.tomcat.max-http-post-size=10485760
server.tomcat.max-swallow-size=10485760

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationShouldBeAtLeast256Bits
jwt.expiration=86400000

# CORS Configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

# Mail Configuration (Yandex)
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=electrocalc@yandex.ru
spring.mail.password=lqxrapijrzyaszag
mail.debug=true

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Test Data Configuration
app.test-data.enabled=true